# Generated by Django 3.1.7 on 2021-03-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210309_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='qq_email',
            field=models.CharField(max_length=100, verbose_name='qq邮箱'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=30, verbose_name='用户名'),
        ),
    ]
