# Generated by Django 3.1.7 on 2021-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_userinfo_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='专栏名称')),
                ('icon', models.CharField(default='fa-home', max_length=30, verbose_name='专栏图标')),
            ],
            options={
                'verbose_name': '专栏',
                'verbose_name_plural': '专栏',
            },
        ),
    ]
