# Generated by Django 3.1.7 on 2021-03-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.column', verbose_name='文章专栏'),
        ),
    ]
