# Generated by Django 3.1.7 on 2021-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='weights',
            field=models.IntegerField(blank=True, default=10, max_length=10, null=True),
        ),
    ]
