# Generated by Django 3.1.7 on 2021-03-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_column_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_tree',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='添加儿子'),
        ),
        migrations.AlterField(
            model_name='column',
            name='weights',
            field=models.IntegerField(blank=True, default=10, max_length=10, null=True, verbose_name='排序权重'),
        ),
    ]
