# Generated by Django 3.1.7 on 2021-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_column_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_file', models.FileField(default='uploads/covers/head.jpg', upload_to='uploads/covers/')),
            ],
        ),
        migrations.AlterField(
            model_name='column',
            name='weights',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='排序权重'),
        ),
    ]
