# Generated by Django 2.2.13 on 2021-03-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210316_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '文件上传', 'verbose_name_plural': '文件上传'},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='cover_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='cover_img',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatars/head.jpg', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(default='covers/1P629140610-3.jpg', upload_to='covers/', verbose_name='文章封面'),
        ),
    ]
