# Generated by Django 2.2.13 on 2021-03-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210316_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default=None, upload_to='avatars/'),
        ),
    ]
