# Generated by Django 3.1.7 on 2021-03-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210316_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upup',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞次数'),
        ),
    ]
