# Generated by Django 2.2.13 on 2021-03-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_article_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.CharField(max_length=30, verbose_name='关于博主')),
                ('site', models.CharField(max_length=30, verbose_name='关于本站')),
                ('promise', models.CharField(max_length=30, verbose_name='本站声明')),
            ],
            options={
                'verbose_name': '关于我',
                'verbose_name_plural': '关于我',
            },
        ),
        migrations.AddField(
            model_name='links',
            name='is_disply',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='image',
            field=models.URLField(default='/media/avatas/head.jpg', verbose_name='头像'),
        ),
    ]
