# Generated by Django 3.1.7 on 2021-03-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210317_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='desc',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='描述'),
        ),
    ]
