# Generated by Django 3.1.7 on 2021-03-18 09:24

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210318_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='me',
            field=mdeditor.fields.MDTextField(verbose_name='关于博主'),
        ),
        migrations.AlterField(
            model_name='about',
            name='promise',
            field=mdeditor.fields.MDTextField(verbose_name='本站声明'),
        ),
        migrations.AlterField(
            model_name='about',
            name='site',
            field=mdeditor.fields.MDTextField(verbose_name='关于本站'),
        ),
    ]
