# Generated by Django 2.2.13 on 2021-04-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210402_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_site',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='添加子站'),
        ),
        migrations.AlterField(
            model_name='column',
            name='url',
            field=models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='路径'),
        ),
    ]
