# Generated by Django 2.2.13 on 2021-04-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20210408_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_md',
            field=models.BooleanField(default=True, verbose_name='是否转md'),
        ),
    ]
