# Generated by Django 3.1.7 on 2021-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_article_is_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_display',
            field=models.BooleanField(default=False, verbose_name='草稿'),
        ),
    ]
